#!/bin/bash

# Set this to the folder where the "ografy" folder lives.
REPO=$HOME/Development/Repositories
# Set this to the directory where the tarballs should be created.
PKG=$HOME/Development/Packages
# Set this to the directory where the environments.
ENV=$HOME/Development/Environments
# Key directory
KEY=$HOME/Development/Security/ssh


case "$1" in
    aws)
        echo "Are you sure you want to deploy tarballs to aws?"
        select yn in "No" "Yes"; do
            case $yn in
                Yes) break;;
                No) exit 0;;
            esac
        done

        KEYS=$KEY/ografy.io
        echo Using aws settings.
        ;;
    virtual)
        KEYS=$KEY/virtual.ografy.io
        echo Using virtual settings.
        ;;
    *)
        echo $"Usage: deploy {aws|virtual}"
        exit 2
        ;;
esac


cd $REPO
tar -czf $PKG/ografy.tar.gz --exclude .git --exclude .idea --exclude ografy/deploy ografy

cd ografy
tar -czf $PKG/deploy.tar.gz --exclude .git --exclude .idea deploy

if [ "$1" = "aws" ]
then
    scp -i $KEYS/ec2-user.pem $PKG/deploy.tar.gz ec2-user@ografy.io:~
    scp -i $KEYS/ografy.pem $PKG/deploy.tar.gz $PKG/ografy.tar.gz ografy@ografy.io:~
else
    # scp -i $KEYS/ografy.pem $PKG/ografy.tar.gz $PKG/deploy.tar.gz ografy@virtual.ografy.io:~

    cd $REPO
    rm -rf $PKG/*
    tar -czf ografy.tar.gz ografy --exclude-vcs --exclude-backups --exclude='.idea'
    mv ografy.tar.gz $PKG

    mkdir
    cp $REPO/ografy/infastructure/modules/ $PKG

    cd $REPO/ografy/infastructure/provision/virtual/web
    vagrant up

    vagrant ssh

fi
