=begin
Arguments Required:

Set environment variable:
export NAME_PW='name:password'
vagrant up

Clear bash history:
cat /dev/null > ~/.bash_history

@Authors Kyle Baran & William Broza
=end

Vagrant.configure('2') do |config|
  config.vm.provider :aws do |aws, override|
   config.vm.box = "dummy"
 	config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    aws.access_key_id = "AKIAIZYJMOY63RTZBRJQ"
    aws.secret_access_key = "JBxoYNiwIMvO8TOgiotVrD6JMpaoQI1uY0lWHCWA"
    aws.keypair_name = "aws_test_2"
    aws.ami = "ami-08842d60"
 	aws.region = "us-east-1"
 	aws.instance_type = "t2.micro"
 	aws.security_groups = "dev"
 	#aws.associate_public_ip = true
    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = "./aws_test_2.pem"
	config.vm.provision "shell", path: "../../deployment_scripts/deploy_bootstrap.sh", args: ENV['NAME_PW']
  end
end
