Vagrant.configure('2') do |config|
  config.vm.provider :aws do |aws, override|
  	config.vm.box = "aws"
	config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    aws.access_key_id = "AKIAIZYJMOY63RTZBRJQ"
    aws.secret_access_key = "JBxoYNiwIMvO8TOgiotVrD6JMpaoQI1uY0lWHCWA"
    aws.keypair_name = "ec2"
    aws.ami = "ami-7747d01e"
    override.ssh.username = "ec2-user"
    override.ssh.private_key_path = "/Users/williambroza/DEV/Vagrant/testaws/ubuntu.pem"
  end
end