path.conf: ./config/
path.data: ./databases/elasticsearch
path.work: ./databases/elasticsearch
path.logs: ./databases/elasticsearch
path.plugins: ./databases/elasticsearch/plugins

network.host: 127.0.0.1
transport.tcp.port: 9300
http.port: 9200
