#!/bin/bash

# Set this to the folder where the "ografy" folder lives.
REPO=$HOME/Development/Repositories
# Set this to the directory where the tarballs should be created.
PKG=$HOME/Development/Packages
# Set this to the directory where the environments.
ENV=$HOME/Development/Environments
# Key directory
KEY=$HOME/Development/Security/ssh


case "$1" in
    aws)

        echo "Are you sure you want to deploy tarballs to aws?"
        select yn in "No" "Yes"; do
            case $yn in
                Yes) break;;
                No) exit 0;;
            esac
        done

        KEYS=$KEY/ografy.io
        echo Using aws settings to deploy.
        ;;

    virtual)

        KEYS=$KEY/virtual.ografy.io
        echo Using virtual settings to deploy.
        ;;

    *)

        echo $"Usage: deploy {aws|virtual}"
        exit 2
        ;;

esac

# Remove files from previous run
rm -rf $PKG/*

# Create ografy and deploy script
cd $REPO
tar -czf $PKG/ografy.tar.gz --exclude .git --exclude .idea --exclude ografy/infrastructure ografy

cd ografy
chmod -R +x infrastructure/packages/*
chmod -R +x infrastructure/platforms/*
tar -czf $PKG/infrastructure.tar.gz --exclude .git --exclude .idea infrastructure

if [ "$1" = "aws" ]
then

    scp -i $KEYS/ec2-user.pem $PKG/infrastructure.tar.gz ec2-user@ografy.io:~
    scp -i $KEYS/ografy.pem $PKG/infrastructure.tar.gz $PKG/ografy.tar.gz ografy@ografy.io:~

else

    # TODO: Create custom CentOS 7 box for vagrant that has user ec2-user and connects using ssh keys instead of passwords. This is to more closely mimmic production
    # scp -i $KEYS/ografy.pem $PKG/ografy.tar.gz $PKG/deploy.tar.gz ografy@virtual.ografy.io:~

    # For diagnostic purposes
    cp $REPO/ografy/infrastructure/provision/virtual/web/web.sh $PKG

    cd $REPO/ografy/infrastructure/provision/virtual/web
    vagrant up

fi
