Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu_aws"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = "AKIAIZYJMOY63RTZBRJQ"
    aws.secret_access_key = "JBxoYNiwIMvO8TOgiotVrD6JMpaoQI1uY0lWHCWA"
    aws.keypair_name = "ubuntu"

    aws.ami = "ami-7747d01e"

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "/Users/williambroza/DEV/Vagrant/testaws/ubuntu.pem"
  end
end