=begin
Arguments Required to be updated in file:

Root Password

@Authors Kyle Baran & William Broza
=end

Vagrant.configure('2') do |config|
	config.vm.provider :virtualbox do |vb, override|
		config.vm.box = "chef/centos-7.0"
		config.vm.synced_folder "../../../../", "/ografy_source"
		vb.customize ["modifyvm", :id, "--memory", "1024"]
		config.vm.provision "shell" do |s|
			s.path = "../../scripts/virtual/deployment.sh"
			s.args = ["vagrant"]
		end
	end
end
