#!/bin/bash


# Set this to the folder where the "ografy" folder lives.
REPO=$HOME/Development/Repositories
# Set this to the directory where the tarballs should be created.
PKG=$HOME/Development/Packages

case "$1" in
    production)
        echo "Are you sure you want to deploy tarballs to production?"
        select yn in "No" "Yes"; do
            case $yn in
                Yes) break;;
                No) exit 0;;
            esac
        done

        KEYS=~/Desktop/Security/ssh/ografy.io
        echo Using production settings.
        ;;
    virtual)
        KEYS=~/Desktop/Security/ssh/virtual.ografy.io
        echo Using virtual settings.
        ;;
    *)
        echo $"Usage: deploy {production|virtual}"
        exit 2
        ;;
esac


cd $REPO
tar -czf $PKG/ografy.tar.gz --exclude .git --exclude .idea --exclude ografy/deploy ografy

cd ografy
tar -czf $PKG/deploy.tar.gz --exclude .git --exclude .idea deploy

if [ "$1" = "production" ]
then
    scp -i $KEYS/ec2-user.pem $PKG/deploy.tar.gz ec2-user@ografy.io:~
    scp -i $KEYS/ografy.pem $PKG/deploy.tar.gz $PKG/ografy.tar.gz ografy@ografy.io:~
else
    scp -i $KEYS/ografy.pem $PKG/ografy.tar.gz $PKG/deploy.tar.gz ografy@virtual.ografy.io:~
fi
