Vagrant.configure('2') do |config|
 config.vm.provider :virtualbox do |vb, override|
		config.vm.box = "chef/centos-6.5"
		config.vm.network "private_network", ip: "192.168.33.10"
		config.vm.synced_folder "../", "/vagrant_data"
		vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
end
