Vagrant.configure('2') do |config|
	config.vm.define :web do |web|
		web.vm.box = "chef/centos-6.5"
		web.vm.network "private_network", ip: "192.168.33.10"
		web.vm.synced_folder "../", "/vagrant_data_web"
		web.vm.provider :virtualbox do |vb, override|
			vb.customize ["modifyvm", :id, "--memory", "1024"]
		end
	end
	
	config.vm.define :db do |db|
		db.vm.box = "chef/centos-6.5"
		db.vm.network "private_network", ip: "192.168.33.11"
		db.vm.synced_folder "../", "/vagrant_data_db"
		db.vm.provider :virtualbox do |vb, override|
			vb.customize ["modifyvm", :id, "--memory", "1024"]
		end
	end
end