#!/bin/sh
#
# nginx - Script that starts and stops the nginx daemon
#
# chkconfig: - 85 15
# description: Nginx is an HTTP(S) server, HTTP(S) reverse proxy and IMAP/POP3 proxy server.
# processname: nginx


source /etc/rc.d/init.d/functions
source /etc/sysconfig/network
[ "$NETWORKING" = "no" ] && exit 0


NGINX="/opt/nginx/sbin/nginx"
NAME=$(basename ${NGINX})
CONF="/opt/nginx/conf/nginx.conf"
LOCK="/var/lock/subsys/nginx"


check() {
    ${NGINX} -t -c ${CONF}
}


reload() {
    check || return $?

    echo -n $"Reloading $NAME"

    killproc ${NGINX} -HUP
    #$NGINX -s reload
    retval=$?

    echo
}


restart() {
    check || return $?
    stop
    sleep 1
    start
}


start() {
    if [ ! -f ${NGINX} ]
    then
        echo -n "$NGINX not found. Aborting..."
        exit 1
    fi

    if [ ! -x ${NGINX} ]
    then
        echo -n "$NGINX is not executable. Aborting..."
        exit 1
    fi

    if [ ! -f ${CONF} ]
    then
        echo -n "$CONF does not exist. Aborting..."
        exit 1
    fi

    echo -n $"Starting $NAME: "

    daemon ${NGINX} -c ${CONF}
    retval=$?
    echo
    [ ${retval} -eq 0 ] && touch ${LOCK}

    return ${retval}
}


stop() {
    echo -n $"Stopping $NAME: "

    killproc ${NAME} -QUIT
    retval=$?
    echo
    [ ${retval} -eq 0 ] && rm -f ${LOCK}

    return ${retval}
}


case "$1" in
    start)
        status ${NAME} >/dev/null 2>&1 && exit 0
        ${1}
        ;;
    stop)
        status ${NAME} >/dev/null 2>&1 || exit 0
        ${1}
        ;;
    check|restart)
        ${1}
        ;;
    reload)
        status ${NAME} >/dev/null 2>&1 || exit 1
        ${1}
        ;;
    status)
        status ${NAME}
        ;;
    *)
        echo "Usage: service nginx {check|reload|restart|start|status|stop}"
        exit 2
        ;;
esac
