=begin

@Authors William Broza
=end

Vagrant.configure('2') do |config|
	config.vm.provider :virtualbox do |vb, override|
		config.vm.box = 'centos6-64'
		config.vm.box_url = 'http://puppet-vagrant-boxes.puppetlabs.com/centos-65-x64-virtualbox-puppet.box'
		config.vm.network "public_network", bridge: 'en0: Wi-Fi (AirPort)'
		vb.customize ["modifyvm", :id, "--memory", "1024"]
		config.vm.provision :puppet do |puppet|
			puppet.module_path = "../../puppet/virtual/modules"
			puppet.manifests_path = "../../puppet/virtual/manifests"
			puppet.manifest_file  = "init.pp"
		end
	end
end
